### PR TITLE
Replaced use of xenstore_data with other_config

### PR DESCRIPTION
**Pull request by asadoughi**
RM11057

### CODE REVIEW

**Comment by insequent** [comment]
-61 line code change, nice.

**Comment by insequent** [comment]
Did something change recently, or is this just an optimization?

**Comment by insequent** [comment]
With the caveat that I still don't know much about xenapi, this LGTM. :snowman:

**Comment by asadoughi** [comment]
Yes, we're changing the internals as a result of discussions with the nova
team to maintain deployment independence and avoid any kind of collision.

**Comment by insequent** [comment]
Working with the VIFs directly does look cleaner.

**Pull request merged**
