### PR TITLE
Synchronize changes with perf testing

### PR DESCRIPTION
**Pull request by Cerberus98**
NCP-1564

* Adds a new index for quark_ip_addresses that helps with reallocation
* Removes the semaphore decorator from select_subnet

### CODE REVIEW

**Comment by asadoughi** [comment]
Looks like neutron/openstack/common/uuidutils.py was replaced with oslo_utils.uuidutils upstream. https://github.com/openstack/neutron/commit/7863399d0feeb0c8ea80346768dd7fd38a78d0e8

**Comment by asadoughi** [comment]
Should be fixed in #405

**Comment by asadoughi** [comment]
Re-kicked the travis tests after #405 was merged, only a flake8 issue this time.

**Comment by Cerberus98** [comment]
thanks Amir. repushed. Hopefully will pass this time

**Comment by mpath** [comment]
:+1:

**Pull request merged**
