### PR TITLE
Fixed problems from oslo_log upgrade

### PR DESCRIPTION
**Pull request by roaet**

### CODE REVIEW

**Comment by roaet** [comment]
This really only should be paired with neutron/master. Any other branch will cause this PR to error like a hoss.

If you need it for your local just merge it. We need to take care when merging this into our environments. We need to wait for https://github.com/openstack/neutron/commit/22328baf1f60719fcaa5b0fbd91c0a3158d09c31
to make it into our neutrons.

**Comment by insequent** [comment]
:+1:  pending tests

**Comment by Cerberus98** [comment]
:hankey: :dragon_face:

**Comment by insequent** [comment]
dragon face, nice

**Comment by roaet** [comment]
Wtfdragon!? :dragon_face: Oh :hankey: !!!!

**Comment by Cerberus98** [comment]
Got tired of waiting for this, so I checked it out and ran it locally:

Ran 776 tests in 96.996s
OK

flake8: commands succeeded
congratulations :)

**Pull request merged**
