### PR TITLE
Update security groups redis client to use security groups specific hash

### PR DESCRIPTION
**Pull request by TMaddox**
Actually expecting hash attr to be "security group rules" not "sg"

### CODE REVIEW

**Comment by Cerberus98** [comment]
:+1: Already ran tests on my machine from this branch.

**Comment by asadoughi** [comment]
:+1: we should be more careful about schema changes once we're in prod. We're having to drop all the data in netdev to test the latest code.

**Comment by TMaddox** [comment]
@asadoughi  :+1: x :100:

**Comment by Cerberus98** [comment]
Screw it, I saw the tests pass on my machine

**Pull request merged**
