### PR TITLE
Used admin context for mac_dealloc

### PR DESCRIPTION
**Pull request by roaet**
JIRA:NCP-1509

Alternative solution is for the tenant to claim the mac address when reallocating.

### CODE REVIEW

**Comment by asadoughi** [comment]
Can you elaborate on the alternative solution? There might be a bugfix for other requests that would be better solved in that way. i.e. if the tenant does not claim a reallocated MAC does the GET /ports still work as expected?

**Comment by Cerberus98** [comment]
I'm confused as to how this broke. The code you've changed here hasn't moved since February of last year. What am I missing?

**Comment by roaet** [comment]
The tenant_id in the DB doesn't change to who currently has it. I don't believe this has any bearing on GET /ports since I am still able to get the port.

**Comment by Cerberus98** [comment]
Oh, because of the mac allocation stuff and tenants

**Comment by roaet** [comment]
https://github.com/roaet/quark/commit/c82fa361b843ecf86b5fa4c57db374cce9f33825

**Comment by roaet** [comment]
There were a lot of changes to mac reallocation or whateverz

**Comment by roaet** [comment]
If we're looking for quick fix due to neutron release I think this is valid. Changing the tenant_id is probably more correct but would take more time.

**Comment by Cerberus98** [comment]
I'm not opposed to this being a quick fix. I don't actually see anything wrong with doing this as admin. I only asked because it wasn't clear to me how it had broken.

**Comment by asadoughi** [comment]
Not blocking this patch, but I'd like to understand better... if it's just tenant_id, then it would be simple to append it here https://github.com/roaet/quark/commit/c82fa361b843ecf86b5fa4c57db374cce9f33825#diff-acddac4b6401f9da48acc821f21c024cR213 But I don't see where tenant_id was being assigned prior to the patch.

**Comment by asadoughi** [comment]
:+1: Merging for now, will settle any confusion later

**Pull request merged**
