### PR TITLE
Add migration for port_vlan_id

### PR DESCRIPTION
**Pull request by ClifHouck**
Also, expose vlan_id on API (port-show)

### CODE REVIEW

**Comment by ClifHouck** [comment]
@Cerberus98 This adds the migration for the port vlan id tag. flake8 checks should pass now.

**Comment by Cerberus98** [comment]
:+1:

**Comment by Cerberus98** [comment]
Also, I forgot add, thank you for doing this so quickly

**Comment by ClifHouck** [comment]
@Cerberus98 No problem, but most credit for this should go to @morgabra since he walked me through setting up a neutron/quark local environment, and how exactly to setup and perform the migration.

**Comment by Cerberus98** [comment]
Ahh, thank you @morgabra as well, then

**Pull request merged**
