### PR TITLE
Adds a test suite for redis_sg_tool

### PR DESCRIPTION
**Pull request by Cerberus98**
RM11379

### CODE REVIEW

**Comment by Cerberus98** [comment]
I'm not sure what's causing this failure, or how to solve it. Tests pass locally for me.

**Comment by asadoughi** [comment]
I'm guessing it passed locally for you because you have a neutron.conf in one of the error message's paths. You need to mock out the the loading of the configuration file. I think there's some prior work somewhere in quark for reference.

**Comment by Cerberus98** [comment]
And pbr appears to be broken.

**Comment by Cerberus98** [comment]
Ahh, actually it's neutron. Neat

**Comment by Cerberus98** [comment]
After a ridiculously exhaustive manual bisect, it looks like it was this guy https://github.com/openstack/neutron/commit/dea4755a3057e507186355bc558968ed57c9ed3b

**Comment by mpath** [comment]
:+1:  :+1: :cloud:

**Pull request merged**
