### PR TITLE
Add use_slave to IP Availability DB Sessions

### PR DESCRIPTION
**Pull request by andyhky**

### CODE REVIEW

**Comment by andyhky** [comment]
Worth noting this requires neutron.db.api to allow the extra argument to get_session.

**Comment by jmeridth** [comment]
@andyhky so we need an upstream change submitted to https://github.com/openstack/neutron/blob/master/neutron/db/api.py#L43 in order for this to work?

**Comment by andyhky** [comment]
I've submitted an internal patch for this to work.

**Comment by asadoughi** [comment]
So, I suppose until we have the necessary neutron code upstream we should make this PR an internal patch, as well?

**Comment by andyhky** [comment]
Closing this PR.

I'll push the change upstream and make an internal quark patch.

**Comment by andyhky** [comment]
https://review.openstack.org/#/c/175491/

**Comment by andyhky** [comment]
Upstream patch is merged.

**Pull request merged**
