### PR TITLE
Update shared_ips.raml

### PR DESCRIPTION
**Pull request by sameersatyam**
Updated attribute names

### CODE REVIEW

**Comment by jmeridth** [comment]
I'm confused.  Thought @asadoughi explained why it needed to be `used_by_tenant_id`.  Are we switching it anyway?

**Comment by asadoughi** [comment]
I asked @sameersatyam to post it here to facilitate discussion. I don't have a strongly held opinion on it being `used_by_tenant_id` as much as @roaet might. To summarize the existing discussion, having it as `tenant_id` would be consistent with other resources. Based on the ownership, in the case of provider networks, `used_by_tenant_id` would make more sense compared to `tenant_id`, but in the case of tenant isolated networks `tenant_id` makes more sense.

**Comment by jmeridth** [comment]
Ah, cool. Thanks for clarifying.

**Comment by roaet** [comment]
I personally don't think this change is necessary. used_by_tenant_id is explicit and is currently how the code works. Should we need to add a tenant_id (for who owns it truly), then we'd have to redo all of whatever we'd be taking out.

**Comment by jmeridth** [comment]
I prefer explicit over implicit as well.  @sameersatyam consistency with other resource that important?

**Comment by roaet** [comment]
I'm fine with this if we change the view. I feel like migrating the DB and losing our explicit attribute is a bad idea.

**Comment by TMaddox** [comment]
:+1:

**Comment by sameersatyam** [comment]
That's good with me and what I was asking all along.

**Pull request merged**
