### PR TITLE
Subnet selection refactoring

### PR DESCRIPTION
**Pull request by Cerberus98**
NCP-1480 Part 2

Refactors select_subnet to hopefully be more readable and allow for
easier future implementation.

### CODE REVIEW

**Comment by Cerberus98** [comment]
Don't merge yet. I want to do some manual testing with this to make sure it's still functional after the refactoring. I wanted to get it out there to see if there were any objections to readability, but I intend to build the final patch on a more readable example, and hopefully everyone agrees with me that this is it.

**Comment by Cerberus98** [comment]
Whatever that neutron setup_hook failure is, I'll check it out later...

**Comment by asadoughi** [comment]
Cool stuff. This looks to be taking the right step incrementally. 

The next steps I suggested in the ticket was replacing a lot of these smaller functions with SQL entirely (one example is `_ip_in_subnet`), which in addition to replacing the locks with compare-and-swap/retry-loop would bridge the divide between the quark reporting and allocation functions.

Is that where you see this going?

**Comment by Cerberus98** [comment]
@asadoughi yeah, more or less. Obviously the first cut here is just to make any subsequent changes a bit easier to review/maintain, so I don't intend to introduce any actual functional changes in this patch.

**Comment by Cerberus98** [comment]
Alright, this passes my stress tests to my satisfaction. No skipped IPs, it consistently produces correct output and still marks subnets as full. I'm sufficiently convinced I didn't change any behavior. I'll work on figuring out whatever the hell happened with tox

**Comment by asadoughi** [comment]
Looks like something to do with this upstream change https://github.com/openstack/neutron/commit/276028cca26af573c14938255e40c58358eabd4a

**Comment by asadoughi** [comment]
I restarted the travis-ci build... appears to have fixed itself overnight as my PR for an empty commit #387 passed.

**Comment by jmeridth** [comment]
Merged #386. should help.

**Comment by asadoughi** [comment]
LGTM

**Pull request merged**
